"""Runs the trained YOLO segmentation model once over every image (both
"before"/unconsumed and "after"/consumed) and caches the detections to disk.

This is a deliberate separate offline step: the Siamese training loop will
run for many epochs over the same images, and re-running YOLO inference
every epoch would be enormously wasteful. Cache once here, then the
training Dataset just reads small JSON files.

Output: one JSON per image stem in MASK_CACHE_DIR, e.g.
  mask_cache/all_markers_shot_20260528_150411.json
  {
    "detections": [
      {"class": "rice", "polygon": [[x, y], ...], "bbox": [x1, y1, x2, y2]}
      ...
    ]
  }
polygon points and bbox are normalized to [0, 1] (fraction of image width/height).

Run:
    python siamese_neural_network/cache_segmentation_masks.py --force
"""

from __future__ import annotations

import argparse
import hashlib
import json
from datetime import datetime, timezone
from pathlib import Path

from ultralytics import YOLO


# ══════════════════════════════════════════════════════════════════════════════
# SECTION 1 — CONFIGURATION
# ══════════════════════════════════════════════════════════════════════════════

MODEL_PATH = Path("/mnt/c/Users/LucaS/Desktop/programmieren_code/ba_thesis/GalleyAI/runs/segment/baseline_v3_current-2/weights/best.pt")

IMAGE_DIRS = [
    Path("data/images"),          # "before" / unconsumed
    Path("data_consumed/images"), # "after" / consumed
]

MASK_CACHE_DIR = Path("mask_cache")

CONF_THRESHOLD = 0.25
IMG_SIZE = 640  # match training imgsz
FORCE_RECOMPUTE = False  # set True to overwrite existing cache entries
CACHE_METADATA_NAME = "_cache_metadata.json"


# ══════════════════════════════════════════════════════════════════════════════
# SECTION 2 — CORE LOGIC
# ══════════════════════════════════════════════════════════════════════════════

def suffix_stem(name: str) -> str:
    """Strips a Label-Studio-style hash prefix like 'a5e6c40__' from a filename stem."""
    stem = Path(name).stem
    if "__" in stem:
        return stem.split("__", 1)[1]
    return stem


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--model", type=Path, default=MODEL_PATH, help="trained YOLO segmentation checkpoint")
    parser.add_argument("--image-dir", type=Path, action="append", dest="image_dirs",
                        help="image directory to cache; repeat for multiple directories")
    parser.add_argument("--cache-dir", type=Path, default=MASK_CACHE_DIR)
    parser.add_argument("--conf", type=float, default=CONF_THRESHOLD)
    parser.add_argument("--imgsz", type=int, default=IMG_SIZE)
    parser.add_argument("--force", action="store_true", default=FORCE_RECOMPUTE,
                        help="overwrite every cached image (required after changing checkpoints)")
    return parser.parse_args()


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def main() -> None:
    args = parse_args()
    model_path = args.model.resolve()
    image_dirs = args.image_dirs or IMAGE_DIRS
    cache_dir = args.cache_dir

    if not model_path.exists():
        raise FileNotFoundError(f"YOLO checkpoint not found: {model_path}")

    model_sha256 = sha256_file(model_path)
    metadata_path = cache_dir / CACHE_METADATA_NAME
    existing_cache = any(p.name != CACHE_METADATA_NAME for p in cache_dir.glob("*.json"))
    if existing_cache and not args.force:
        raise RuntimeError(
            f"Cache already contains predictions in {cache_dir.resolve()}. "
            "Pass --force to prove that all entries were generated by the selected checkpoint."
        )

    print(f"Loading model from {model_path} (sha256={model_sha256[:12]}...)...")
    model = YOLO(str(model_path))

    total = 0
    skipped_cached = 0
    processed = 0

    for images_dir in image_dirs:
        if not images_dir.exists():
            raise FileNotFoundError(f"Images dir not found: {images_dir.resolve()}")

        image_paths = sorted(
            p for p in images_dir.iterdir()
            if p.suffix.lower() in {".jpg", ".jpeg", ".png"}
        )
        print(f"\n{images_dir}: {len(image_paths)} image(s)")

        for image_path in image_paths:
            total += 1
            stem = suffix_stem(image_path.name)
            out_path = cache_dir / f"{stem}.json"

            if out_path.exists() and not args.force:
                skipped_cached += 1
                continue

            result = model.predict(
                source=str(image_path), conf=args.conf, imgsz=args.imgsz, verbose=False
            )[0]
            detections = []
            if result.masks is not None:
                classes = result.boxes.cls.tolist()
                for cls_idx, polygon, bbox in zip(classes, result.masks.xyn, result.boxes.xyxyn.tolist()):
                    detections.append({
                        "class": result.names[int(cls_idx)],
                        "polygon": polygon.tolist(),
                        "bbox": bbox,
                    })
            out_path.parent.mkdir(parents=True, exist_ok=True)
            with out_path.open("w", encoding="utf-8") as fh:
                json.dump({"detections": detections}, fh)
            processed += 1
            if processed % 25 == 0:
                print(f"  ...{processed} newly cached")

    print(f"\nDone. total images seen: {total}, newly cached: {processed}, "
          f"already cached (skipped): {skipped_cached}")
    metadata = {
        "generated_at_utc": datetime.now(timezone.utc).isoformat(),
        "model_path": str(model_path),
        "model_sha256": model_sha256,
        "class_names": list(model.names.values()),
        "confidence_threshold": args.conf,
        "image_size": args.imgsz,
        "image_dirs": [str(path.resolve()) for path in image_dirs],
        "images_seen": total,
        "images_processed": processed,
    }
    cache_dir.mkdir(parents=True, exist_ok=True)
    with metadata_path.open("w", encoding="utf-8") as fh:
        json.dump(metadata, fh, indent=2)
    print(f"Cache written to: {cache_dir.resolve()}")
    print(f"Provenance written to: {metadata_path.resolve()}")


if __name__ == "__main__":
    main()
